services:
  backend:
    build:
     context: ./server
    container_name : authlib-backend
    ports :
      - "8000:8000"

  frontend:
    build:
      context : ./client
    container_name: authlib-frontend
    ports : 
      - "3000:3000"
    depends_on:
      - backend